### ISSUE TITLE
Feat. request: getter for annotation ID 

### ISSUE THREAD

**Issue by keighrim** [weblicht/wlfxb#12]
Most of API's defined in [eu.clarin.weblicht.wlfxb.tc.api](https://github.com/weblicht/wlfxb/tree/master/src/main/java/eu/clarin/weblicht/wlfxb/tc/api) (and their implementations in [eu.clarin.weblicht.wlfxb.tc.xb](https://github.com/weblicht/wlfxb/tree/master/src/main/java/eu/clarin/weblicht/wlfxb/tc/xb)) do not have a public method to get the identifiers of individual annotations. For example, `SentenceStored` class has [`sentenceId`](https://github.com/weblicht/wlfxb/blob/master/src/main/java/eu/clarin/weblicht/wlfxb/tc/xb/SentenceStored.java#L42) field, but it's protected. 
We are writing [a piece of code](https://github.com/lappsgrid-incubator/tcf-converter-prototype) for converting TCF into a different format, and it would be great to have a getter method for those identifiers. 
Thanks!

**Comment by qiuwei** [comment]
@keighrim 

Hi, it definitely doable. The only thing I want to point out is that, the annotation Id might not be presented in every tcf file, because it's not required by the TCF spec.

However, if the tcf file is created using this library, the Ids should be presented. However, I know a few weblicht services created by other centers do not rely on this library.

Fazleh has already started working on this, maybe you can contact him directly how we can work this out.

**Comment by keighrim** [comment]
Closing this, see elahi123/wlfxb#1 for discussion.
